name: Push-to-EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2 (with Security Enhancements)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Install SSH dependencies (if needed)
        run: |
          sudo apt-get update
          sudo apt-get install openssh-client -y  # Install openssh-client if not present

      - name: Grant temporary SSH permissions (recommended)
        run: |
          umask 077  # Set stricter permissions for the temporary key file
          echo ${{ secrets.EC2_SSH_KEY }} | tr -d '\r' > id_rsa  # Decrypt and write key securely
          chmod 600 id_rsa  # Set stricter permissions for the key file
          eval "$(ssh-agent -s)"  # Start the SSH agent
          ssh-add id_rsa  # Add the temporary key to the agent
          ssh-keyscan ${{ secrets.REMOTE_HOST }} >> known_hosts  # Add host to known_hosts (optional)

      - name: Deploy files securely using SFTP (recommended)
        uses: sftp-deploy/sftp-deploy@v1.4.0
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          local_dir: ./
          remote_dir: /repos/commerce
          privateKey: ${{ secrets.EC2_SSH_KEY }}  # Pass key securely without exposing in workflow logs

      - name: Remove temporary SSH resources (recommended)
        run: |
          ssh-agent -k  # Kill the SSH agent
          rm -f id_rsa known_hosts  # Remove temporary files

